# Generated by Django 4.2.3 on 2023-08-07 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('num_semestre', models.IntegerField()),
                ('carga_horaria', models.IntegerField()),
                ('departamento', models.CharField(max_length=80)),
                ('obrigatorio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prof', models.CharField(max_length=80)),
                ('horas_semanais', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_turma', models.PositiveSmallIntegerField()),
                ('horario', models.CharField(max_length=15)),
                ('cod_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma_disciplina', to='horarios.componentecurricular')),
                ('professor', models.ManyToManyField(blank=True, null=True, related_name='turma_professor', to='horarios.professor')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(blank=True, null=True, related_name='professor_turma', to='horarios.turma'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('cod_componente', 'num_turma'), name='unique_cod_componente_num_turma'),
        ),
    ]
