# Generated by Django 4.2.3 on 2023-07-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponenteCurricular',
            new_name='Componente_curricular',
        ),
    ]
