# Generated by Django 4.2.3 on 2023-08-17 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentecurricular',
            name='codigo',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='horas_semanais',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddConstraint(
            model_name='componentecurricular',
            constraint=models.CheckConstraint(check=models.Q(('num_semestre__gte', '0')), name='semestre_maior_igual_0'),
        ),
        migrations.AddConstraint(
            model_name='componentecurricular',
            constraint=models.CheckConstraint(check=models.Q(('num_semestre__lte', '6')), name='semestre_menor_igual_6'),
        ),
        migrations.AddConstraint(
            model_name='componentecurricular',
            constraint=models.CheckConstraint(check=models.Q(('carga_horaria__gte', '0')), name='carga_horaria_maior_0'),
        ),
    ]
