# Generated by Django 4.2.3 on 2023-07-27 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_rename_componentecurricular_componente_curricular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_prof', models.CharField(max_length=80)),
                ('horas_semanais', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('num_turma', models.IntegerField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=15)),
                ('cod_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma_disciplina', to='horarios.componente_curricular')),
                ('professor', models.ManyToManyField(related_name='turma_professor', to='horarios.professor')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(related_name='professor_turma', to='horarios.turma'),
        ),
    ]
