# Generated by Django 4.2.3 on 2023-07-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_professor_turma_professor_turmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='horas_semanais',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(blank=True, null=True, related_name='professor_turma', to='horarios.turma'),
        ),
    ]
