# Generated by Django 4.2.3 on 2023-07-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_alter_professor_horas_semanais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='horas_semanais',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
