# Generated by Django 4.2.3 on 2023-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_alter_componentecurricular_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nome_prof',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
