# Generated by Django 4.2.3 on 2023-08-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_alter_professor_nome_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentecurricular',
            old_name='nome',
            new_name='nome_comp',
        ),
    ]
