# Generated by Django 4.2.3 on 2023-07-28 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_alter_professor_horas_semanais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('num_semestre', models.IntegerField()),
                ('carga_horaria', models.IntegerField(default=0)),
                ('departamento', models.CharField(max_length=80)),
                ('obrigatorio', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ManyToManyField(blank=True, null=True, related_name='turma_professor', to='horarios.professor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='cod_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma_disciplina', to='horarios.componentecurricular'),
        ),
        migrations.DeleteModel(
            name='Componente_curricular',
        ),
    ]
