# Generated by Django 4.2.3 on 2023-07-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_componentecurricular_turma_id_alter_professor_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turma',
            name='horarios_turma_unique',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='id',
        ),
        migrations.AlterField(
            model_name='turma',
            name='num_turma',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
