# Generated by Django 4.2.3 on 2023-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_rename_nome_componentecurricular_nome_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentecurricular',
            name='num_semestre',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='componentecurricular',
            constraint=models.CheckConstraint(check=models.Q(('num_semestre', 0), ('obrigatorio', True), _negated=True), name='num_semestre_necessario_componente_obrigatorio'),
        ),
    ]
