# Generated by Django 4.2.3 on 2023-09-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_alter_componentecurricular_num_semestre_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='componentecurricular',
            name='num_semestre_necessario_componente_obrigatorio',
        ),
        migrations.AddConstraint(
            model_name='componentecurricular',
            constraint=models.CheckConstraint(check=models.Q(('num_semestre', '0'), ('obrigatorio', True), _negated=True), name='semestre_diferente_zero_componente_obrigatorio'),
        ),
    ]
