# Generated by Django 4.2.3 on 2023-09-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0008_remove_componentecurricular_num_semestre_necessario_componente_obrigatorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='num_vagas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
